"""initial schema

Revision ID: 52e64e952e47
Revises: 
Create Date: 2026-09-11 11:42:46.329234
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '52e64e952e47'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bulk_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bulk_job_id', sa.String(length=36), nullable=False),
    sa.Column('row_index', sa.Integer(), nullable=False),
    sa.Column('channel_name', sa.String(length=255), nullable=False),
    sa.Column('playback_url', sa.Text(), nullable=False),
    sa.Column('origin_url', sa.Text(), nullable=True),
    sa.Column('cdn_url', sa.Text(), nullable=True),
    sa.Column('ssai_url', sa.Text(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('child_job_id', sa.String(length=36), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('verdict_status', sa.String(length=48), nullable=True),
    sa.Column('owner', sa.String(length=32), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bulk_items_bulk_job_id'), 'bulk_items', ['bulk_job_id'], unique=False)
    op.create_index(op.f('ix_bulk_items_status'), 'bulk_items', ['status'], unique=False)
    op.create_table('channels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('channel_ref', sa.String(length=128), nullable=True),
    sa.Column('country', sa.String(length=8), nullable=True),
    sa.Column('content_provider', sa.String(length=255), nullable=True),
    sa.Column('cdn', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channels_channel_ref'), 'channels', ['channel_ref'], unique=False)
    op.create_index(op.f('ix_channels_name'), 'channels', ['name'], unique=False)
    op.create_table('playlist_snapshots',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('stream_layer', sa.String(length=16), nullable=False),
    sa.Column('variant', sa.String(length=64), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('raw', sa.Text(), nullable=False),
    sa.Column('msn', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_playlist_snapshots_job_id'), 'playlist_snapshots', ['job_id'], unique=False)
    op.create_index('ix_playlist_snapshots_job_variant_ts', 'playlist_snapshots', ['job_id', 'variant', 'ts'], unique=False)
    op.create_index(op.f('ix_playlist_snapshots_ts'), 'playlist_snapshots', ['ts'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('channel_name', sa.String(length=255), nullable=True),
    sa.Column('job_type', sa.String(length=16), nullable=False),
    sa.Column('format', sa.String(length=8), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('verdict_status', sa.String(length=48), nullable=True),
    sa.Column('owner', sa.String(length=32), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_created_at'), 'reports', ['created_at'], unique=False)
    op.create_index(op.f('ix_reports_job_id'), 'reports', ['job_id'], unique=False)
    op.create_table('samples_player',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event', sa.String(length=32), nullable=False),
    sa.Column('buffer_s', sa.Float(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('bitrate', sa.Integer(), nullable=True),
    sa.Column('dropped_frames', sa.Integer(), nullable=True),
    sa.Column('stall_duration_s', sa.Float(), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_samples_player_job_id'), 'samples_player', ['job_id'], unique=False)
    op.create_index(op.f('ix_samples_player_ts'), 'samples_player', ['ts'], unique=False)
    op.create_table('samples_playlist',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('stream_layer', sa.String(length=16), nullable=False),
    sa.Column('variant', sa.String(length=64), nullable=False),
    sa.Column('msn', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('last_msn', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('dsn', sa.Integer(), nullable=False),
    sa.Column('seg_count', sa.Integer(), nullable=False),
    sa.Column('target_duration', sa.Float(), nullable=True),
    sa.Column('window_s', sa.Float(), nullable=False),
    sa.Column('freshness_s', sa.Float(), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=False),
    sa.Column('ttfb_ms', sa.Float(), nullable=True),
    sa.Column('total_ms', sa.Float(), nullable=False),
    sa.Column('bytes', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_samples_playlist_job_id'), 'samples_playlist', ['job_id'], unique=False)
    op.create_index('ix_samples_playlist_job_variant_ts', 'samples_playlist', ['job_id', 'variant', 'ts'], unique=False)
    op.create_index(op.f('ix_samples_playlist_ts'), 'samples_playlist', ['ts'], unique=False)
    op.create_table('samples_segment',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('stream_layer', sa.String(length=16), nullable=False),
    sa.Column('variant', sa.String(length=64), nullable=False),
    sa.Column('msn', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('uri_hash', sa.String(length=64), nullable=False),
    sa.Column('uri', sa.Text(), nullable=False),
    sa.Column('bytes', sa.Integer(), nullable=False),
    sa.Column('duration_declared', sa.Float(), nullable=True),
    sa.Column('duration_actual', sa.Float(), nullable=True),
    sa.Column('download_ms', sa.Float(), nullable=False),
    sa.Column('ttfb_ms', sa.Float(), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=False),
    sa.Column('measured_kbps', sa.Float(), nullable=True),
    sa.Column('pts_start', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('pts_end', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('av_skew_ms', sa.Float(), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_samples_segment_job_id'), 'samples_segment', ['job_id'], unique=False)
    op.create_index('ix_samples_segment_job_variant_ts', 'samples_segment', ['job_id', 'variant', 'ts'], unique=False)
    op.create_index(op.f('ix_samples_segment_ts'), 'samples_segment', ['ts'], unique=False)
    op.create_table('settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('virtual_buffer',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('variant', sa.String(length=64), nullable=False),
    sa.Column('level_s', sa.Float(), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_virtual_buffer_job_id'), 'virtual_buffer', ['job_id'], unique=False)
    op.create_index('ix_virtual_buffer_job_variant_ts', 'virtual_buffer', ['job_id', 'variant', 'ts'], unique=False)
    op.create_index(op.f('ix_virtual_buffer_ts'), 'virtual_buffer', ['ts'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=True),
    sa.Column('channel_name', sa.String(length=255), nullable=True),
    sa.Column('parent_job_id', sa.String(length=36), nullable=True),
    sa.Column('playback_url', sa.Text(), nullable=True),
    sa.Column('origin_url', sa.Text(), nullable=True),
    sa.Column('cdn_url', sa.Text(), nullable=True),
    sa.Column('ssai_url', sa.Text(), nullable=True),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verdict', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_parent_job_id'), 'jobs', ['parent_job_id'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_index(op.f('ix_jobs_type'), 'jobs', ['type'], unique=False)
    op.create_table('findings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('rule_id', sa.String(length=16), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('layer', sa.String(length=24), nullable=False),
    sa.Column('stream_layer', sa.String(length=16), nullable=False),
    sa.Column('owner', sa.String(length=24), nullable=False),
    sa.Column('variant', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('root_cause', sa.Text(), nullable=False),
    sa.Column('fix', sa.Text(), nullable=False),
    sa.Column('rebuffer_impact', sa.String(length=12), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('layer_presence', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_findings_job_id'), 'findings', ['job_id'], unique=False)
    op.create_index(op.f('ix_findings_owner'), 'findings', ['owner'], unique=False)
    op.create_index(op.f('ix_findings_rule_id'), 'findings', ['rule_id'], unique=False)
    op.create_index(op.f('ix_findings_severity'), 'findings', ['severity'], unique=False)
    op.create_table('incidents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('variant', sa.String(length=64), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_s', sa.Float(), nullable=False),
    sa.Column('cause_finding_ids', sa.JSON(), nullable=False),
    sa.Column('cause_chain', sa.JSON(), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidents_job_id'), 'incidents', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_incidents_job_id'), table_name='incidents')
    op.drop_table('incidents')
    op.drop_index(op.f('ix_findings_severity'), table_name='findings')
    op.drop_index(op.f('ix_findings_rule_id'), table_name='findings')
    op.drop_index(op.f('ix_findings_owner'), table_name='findings')
    op.drop_index(op.f('ix_findings_job_id'), table_name='findings')
    op.drop_table('findings')
    op.drop_index(op.f('ix_jobs_type'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_parent_job_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_virtual_buffer_ts'), table_name='virtual_buffer')
    op.drop_index('ix_virtual_buffer_job_variant_ts', table_name='virtual_buffer')
    op.drop_index(op.f('ix_virtual_buffer_job_id'), table_name='virtual_buffer')
    op.drop_table('virtual_buffer')
    op.drop_table('settings')
    op.drop_index(op.f('ix_samples_segment_ts'), table_name='samples_segment')
    op.drop_index('ix_samples_segment_job_variant_ts', table_name='samples_segment')
    op.drop_index(op.f('ix_samples_segment_job_id'), table_name='samples_segment')
    op.drop_table('samples_segment')
    op.drop_index(op.f('ix_samples_playlist_ts'), table_name='samples_playlist')
    op.drop_index('ix_samples_playlist_job_variant_ts', table_name='samples_playlist')
    op.drop_index(op.f('ix_samples_playlist_job_id'), table_name='samples_playlist')
    op.drop_table('samples_playlist')
    op.drop_index(op.f('ix_samples_player_ts'), table_name='samples_player')
    op.drop_index(op.f('ix_samples_player_job_id'), table_name='samples_player')
    op.drop_table('samples_player')
    op.drop_index(op.f('ix_reports_job_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_created_at'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_playlist_snapshots_ts'), table_name='playlist_snapshots')
    op.drop_index('ix_playlist_snapshots_job_variant_ts', table_name='playlist_snapshots')
    op.drop_index(op.f('ix_playlist_snapshots_job_id'), table_name='playlist_snapshots')
    op.drop_table('playlist_snapshots')
    op.drop_index(op.f('ix_channels_name'), table_name='channels')
    op.drop_index(op.f('ix_channels_channel_ref'), table_name='channels')
    op.drop_table('channels')
    op.drop_index(op.f('ix_bulk_items_status'), table_name='bulk_items')
    op.drop_index(op.f('ix_bulk_items_bulk_job_id'), table_name='bulk_items')
    op.drop_table('bulk_items')
    # ### end Alembic commands ###
